#!/bin/sh
cd /home/bittboy/git/invoker/invoker
make clean
make PLATFORM=RG-350
cp /home/bittboy/git/invoker/invoker/invoker.dge /home/bittboy/git/simplemenu/simplemenu/output/invoker.dge
cd /home/bittboy/git/simplemenu/simplemenu/
make clean
make PLATFORM=RG-350
cd output
./make_opk.sh
scp simplemenu.opk root@10.1.1.2:/media/data/apps
