#!/bin/sh

# author MashTec
# modified by FGL82

if [ -f /media/data/apps/SimpleMenu-OD.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/data/apps/SimpleMenu-OD.opk
elif [ -f /media/sdcard/apps/SimpleMenu-OD.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/apps/SimpleMenu-OD.opk
elif [ -f /media/sdcard/APPS/SimpleMenu-OD.opk ]; then
    /usr/bin/opkrun -m default.gcw0.desktop /media/sdcard/APPS/SimpleMenu-OD.opk    
else
    /usr/bin/gmenu2x
fi
